import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import endent from "endent"
import { part1, part2 } from "./index.ts"

describe("day 8", () => {
  test("part 1 example", () => {
    const example = endent`
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
    `

    const result = part1(example)

    expect(result).toEqual("14")
  })

  test("part 1 input", async () => {
    const result = part1((await readFile("src/day8/input.txt")).toString())

    expect(result).toEqual("313")
  })

  test("part 2 example", () => {
    const example = endent`
      ............
      ........0...
      .....0......
      .......0....
      ....0.......
      ......A.....
      ............
      ............
      ........A...
      .........A..
      ............
      ............
    `

    const result = part2(example)

    expect(result).toEqual("34")
  })

  test("part 2 example 2", () => {
    const example = endent`
      T.........
      ...T......
      .T........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
      ..........
    `

    const result = part2(example)

    expect(result).toEqual("9")
  })

  test("part 2 input", async () => {
    const result = part2((await readFile("src/day8/input.txt")).toString())

    expect(result).toEqual("1064")
  })
})
